version: '3.3'

services:
  redis:
    image: redis
    container_name: redis
    networks:
      - redis-net
    ports:
      - 6379:6379

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    volumes:
      - redis-vol:/db
    networks:
      - redis-net
    ports:
      - 8001:8001

volumes:
  redis-vol:
    driver: local

networks:
  redis-net:
    driver: bridge