version: "3.8"

services:
  redis:
    image: redis:${REDIS_VERISON:-6.2.5}
    command: redis-server --requirepass ${REDIS_PASSWORD:-password}
    container_name: redis
    volumes:
      - ./redis.conf:/etc/redis/redis.conf.default
    networks:
      - net
    ports:
      - ${REDIS_PORT:-6379}:6379
    environment:
      TZ: ${TIMEZONE:-"Asia/Bangkok"}
    restart: always

  redis-insight:
    image: redislabs/redisinsight:${INSIGHT_VERSION:-latest}
    container_name: redis-insight
    volumes:
      - vol:/db
    networks:
      - net
    ports:
      - ${INSIGHT_PORT:-8001}:8001
    environment:
      TZ: ${TIMEZONE:-"Asia/Bangkok"}
    depends_on:
      - redis
    restart: always

volumes:
  vol:
    driver: local

networks:
  net:
    driver: bridge
