version: '3.3'

services:
  redis:
    build: 
      context: .
      args: 
        - conf=./redis.conf
      dockerfile: Dockerfile
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    container_name: redis
    networks:
      - net
    ports:
      - ${REDIS_PORT}:6379
    environment: 
      - TZ=${TIMEZONE}
    restart: always

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    volumes:
      - vol:/db
    networks:
      - net
    ports:
      - ${INSIGHT_PORT}:8001
    environment: 
      - TZ=${TIMEZONE}
    depends_on: 
      - redis
    restart: always

volumes:
  vol:
    driver: local

networks:
  net:
    driver: bridge