version: "3.8"

services:
  redis:
    image: redis:${REDIS_VERSION:-7.0.7}
    container_name: redis
    command:
      - "--requirepass ${REDIS_PASSWORD:-password}"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 3
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis_server_volume:/data
    networks:
      - redis_network
    ports:
      - ${REDIS_PORT:-6379}:6379
    environment:
      TZ: ${TIMEZONE:-"Asia/Bangkok"}
    restart: on-failure

  redis-insight:
    image: redislabs/redisinsight:${INSIGHT_VERSION:-1.13.0}
    container_name: redis-insight
    volumes:
      - redis_insight_volume:/db
    networks:
      - redis_network
    ports:
      - ${INSIGHT_PORT:-8001}:8001
    environment:
      TZ: ${TIMEZONE:-"Asia/Bangkok"}
    depends_on:
      - redis
    restart: always

volumes:
  redis_server_volume:
    name: redis_server_volume
    driver: local
  redis_insight_volume:
    name: redis_insight_volume
    driver: local

networks:
  redis_network:
    name: redis_network
    driver: bridge
